cfg = {}

cfg.pos = vec(-57.295837402344,-1096.4705810547,26.42234992981)

cfg.timer = 30 --Tiden man kan prøve køre bilen
cfg.testpos = vec(-937.09912109375,-3274.4538574219,13.579298019409) -- Stedet man test kører bilen

cfg.vehicles = {
    --[[
        {name = "Navn", model = "Spawn", price = Pris, category = "Kategori", imglink = "Billed"},
    ]]

    -- KOMPAKTE
    {name = "Blista",model = "Blista",price = 50000,category = "Kompakte",imglink = "https://wiki.gtanet.work/images/5/58/Blista.png"},
    {name = "Blista Compact",model = "Blista2",price = 40000,category = "Kompakte",imglink = "https://wiki.gtanet.work/images/0/0c/Blista2.png"},
    {name = "Brioso R/A",model = "Brioso",price = 75000,category = "Kompakte",imglink = "https://wiki.gtanet.work/images/6/6f/Brioso.png"},
    {name = "Dilettante",model = "Dilettante",price = 50000,category = "Kompakte",imglink = "https://wiki.gtanet.work/images/b/b9/Dilettante.png"},
    {name = "Issi",model = "Issi2",price = 60000,category = "Kompakte",imglink = "https://wiki.gtanet.work/images/0/0b/Issi2.png"},
    {name = "Issi Classic",model = "Issi3",price = 40000,category = "Kompakte",imglink = "https://static.wikia.nocookie.net/gtawiki/images/9/9f/IssiClassic-GTAO-front.png/revision/latest?cb=20180325152715"},
    {name = "Panto",model = "Panto",price = 60000,category = "Kompakte",imglink = "https://wiki.gtanet.work/images/e/e5/Panto.png"},
    {name = "Prairie",model = "Prairie",price = 75000,category = "Kompakte",imglink = "https://wiki.gtanet.work/images/3/3d/Prairie.png"},
    {name = "Rhapsody",model = "Rhapsody",price = 50000,category = "Kompakte",imglink = "https://wiki.gtanet.work/images/e/e2/Rhapsody.png"},
    {name = "futo",model = "futo",price = 112500,category = "Kompakte",imglink = "https://static.wikia.nocookie.net/gtawiki/images/6/67/Futo-GTAV-front.PNG/revision/latest?cb=20180726155611"},

    -- Coupéer
    {name = "Specter",model = "specter",price = 2700000,category = "Coupéer",imglink = "https://wiki.gtanet.work/images/2/23/specter.png"},
    {name = "Specter CTM",model = "specter2",price = 2700000,category = "Coupéer",imglink = "https://wiki.gtanet.work/images/d/dc/specter2.png"},
    {name = "Cognoscenti Cabrio",model = "cogcabrio",price = 2300000,category = "Coupéer",imglink = "https://wiki.gtanet.work/images/1/1b/CogCabrio.png"},
    {name = "F620",model = "f620",price = 2300000,category = "Coupéer",imglink = "https://wiki.gtanet.work/images/2/21/F620.png"},
    {name = "Felon GT",model = "felon2",price = 1900000,category = "Coupéer",imglink = "https://wiki.gtanet.work/images/6/6e/Felon2.png"},
    {name = "Jackal",model = "Jackal",price = 1600000,category = "Coupéer",imglink = "https://wiki.gtanet.work/images/7/70/Jackal.png"},
    {name = "Oracle",model = "Oracle",price = 1600000,category = "Coupéer",imglink = "https://wiki.gtanet.work/images/1/17/Oracle.png"},
    {name = "Oracle XS",model = "Oracle2",price = 1700000,category = "Coupéer",imglink = "https://wiki.gtanet.work/images/4/4d/Oracle2.png"},
    {name = "Sentinel",model = "Sentinel",price = 900000,category = "Coupéer",imglink = "https://wiki.gtanet.work/images/9/91/Sentinel.png"},
    {name = "Sentinel XS",model = "sentinel2",price = 900000,category = "Coupéer",imglink = "https://wiki.gtanet.work/images/d/dd/Sentinel2.png"},
    {name = "Windsor",model = "windsor",price = 2000000,category = "Coupéer",imglink = "https://wiki.gtanet.work/images/2/2d/Windsor.png"},
    {name = "Windsor Drop",model = "windsor2",price = 2200000,category = "Coupéer",imglink = "https://wiki.gtanet.work/images/5/57/Windsor2.png"},
    {name = "Zion",model = "Zion",price = 1100000,category = "Coupéer",imglink = "https://wiki.gtanet.work/images/5/51/Zion.png"},
    {name = "Zion Cabrio",model = "Zion2",price = 1300000,category = "Coupéer",imglink = "https://wiki.gtanet.work/images/f/f2/Zion2.png"},

    -- Sports
    {name = "Neon",model = "Neon",price = 1500000,category = "SportsBi",imglink = "http://www.gta5rides.com/vehicleImages/cropped/neon.jpg.jpg"},
    {name = "Comet SR",model = "comet5",price = 1145000,category = "SportsBi",imglink = "http://3.bp.blogspot.com/-Ih9voX6JfoI/VKrecV95TwI/AAAAAAAAAxo/457LvbzTgz8/s1600/BTX9r6x.jpg"},
    {name = "Comet",model = "Comet3",price = 550000,category = "SportsBi",imglink = "https://static.wikia.nocookie.net/gtawiki/images/a/a0/CometRetroCustom-GTAO-front.png/revision/latest?cb=20161213201950"},
    {name = "Pariah",model = "pariah",price = 1420000,category = "SportsBi",imglink = "https://static.wikia.nocookie.net/gtawiki/images/f/ff/Pariah-GTAO-front.png/revision/latest?cb=20171218203236"},
    {name = "Banshee",model = "Banshee",price = 105000,category = "SportsBi",imglink = "https://wiki.gtanet.work/images/d/d3/Banshee.png"},
    {name = "Bestia GTS",model = "bestiagts",price = 610000,category = "SportsBi",imglink = "https://wiki.gtanet.work/images/d/dd/BestiaGTS.png"},
    {name = "Buffalo",model = "buffalo",price = 750000,category = "SportsBi",imglink = "https://wiki.gtanet.work/images/0/0a/Buffalo.png"},
    {name = "Buffalo S",model = "buffalo2",price = 960000,category = "SportsBi",imglink = "https://wiki.gtanet.work/images/2/2c/Buffalo2.png"},
    {name = "Carbonizzare",model = "carbonizzare",price = 195000,category = "SportsBi",imglink = "https://wiki.gtanet.work/images/4/43/Carbonizzare.png"},
    {name = "Coquette",model = "coquette",price = 138000,category = "SportsBi",imglink = "https://wiki.gtanet.work/images/d/d6/Coquette.png"},
    {name = "Drift Tampa",model = "tampa2",price = 995000,category = "SportsBi",imglink = "https://wiki.gtanet.work/images/a/af/Tampa2.png"},
    {name = "Feltzer",model = "feltzer2",price = 145000,category = "SportsBi",imglink = "https://wiki.gtanet.work/images/7/7c/Feltzer2.png"},
    {name = "Furore GT",model = "furoregt",price = 448000,category = "SportsBi",imglink = "https://wiki.gtanet.work/images/c/cb/Furoregt.png"},
    {name = "Fusilade",model = "fusilade",price = 650000,category = "SportsBi",imglink = "https://wiki.gtanet.work/images/5/56/Fusilade.png"},
    {name = "Jester",model = "Jester",price = 240000,category = "SportsBi",imglink = "https://wiki.gtanet.work/images/e/e0/Jester.png"},
    {name = "Kuruma",model = "Kuruma",price = 350000,category = "SportsBi",imglink = "https://wiki.gtanet.work/images/8/8f/Kuruma.png"},
    {name = "Lynx",model = "Lynx",price = 126350,category = "SportsBi",imglink = "https://wiki.gtanet.work/images/b/b8/Lynx.png"},
    {name = "Massacro",model = "massacro",price = 1735000,category = "SportsBi",imglink = "https://wiki.gtanet.work/images/7/78/Massacro.png"},
    {name = "Omnis",model = "Omnis",price = 275000,category = "SportsBi",imglink = "https://wiki.gtanet.work/images/1/12/Omnis.png"},
    {name = "Penumbra",model = "penumbra",price = 385000,category = "SportsBi",imglink = "https://wiki.gtanet.work/images/9/93/Penumbra.png"},
    {name = "Rapid GT",model = "rapidgt",price = 701000,category = "SportsBi",imglink = "https://wiki.gtanet.work/images/b/b5/RapidGT.png"},
    {name = "Rapid GT Convertible",model = "rapidgt2",price = 600000,category = "SportsBi",imglink = "https://wiki.gtanet.work/images/5/53/RapidGT2.png"},
    {name = "Schafter V12",model = "schafter3",price = 132000,category = "SportsBi",imglink = "https://wiki.gtanet.work/images/a/a9/Schafter3.png"},
    {name = "Surano",model = "surano",price = 140000,category = "SportsBi",imglink = "https://wiki.gtanet.work/images/9/96/Surano.png"},
    {name = "Tropos",model = "tropos",price = 116000,category = "SportsBi",imglink = "https://wiki.gtanet.work/images/7/71/Tropos.png"},
    {name = "Verkierer",model = "verlierer2",price = 100000,category = "SportsBi",imglink = "https://wiki.gtanet.work/images/8/81/Verlierer2.png"},
    {name = "Schlagen GT",model = "Schlagen",price = 816000,category = "SportsBi",imglink = "https://static.wikia.nocookie.net/gtawiki/images/4/42/SchlagenGT-GTAO-front.png/revision/latest?cb=20190107163325"},
    {name = "Khamelion",model = "khamelion",price = 695000,category = "SportsBi",imglink = "https://wiki.gtanet.work/images/2/2e/Khamelion.png"},
    {name = "Ruston",model = "Ruston",price = 1300000,category = "SportsBi",imglink = "https://wiki.gtanet.work/images/b/ba/Ruston.png"},
    {name = "Dominator GTX",model = "dominator3",price = 100000,category = "SportsBi",imglink = "https://i.pinimg.com/originals/d8/08/82/d808824e2c63a7cd1c29c22adb356201.jpg"},
    {name = "Sultan RS",model = "sultanrs",price = 648000,category = "SportsBi",imglink = "https://wiki.gtanet.work/images/1/11/SultanRS.png"},

    -- Sports klassikere
    {name = "Retinue",model = "retinue",price = 615000,category = "Sportsk",imglink = "https://static.wikia.nocookie.net/gtawiki/images/b/b8/Retinue-GTAO-front.png/revision/latest?cb=20171220192309"},
    {name = "Torero",model = "Torero",price = 998000,category = "Sportsk",imglink = "https://static.wikia.nocookie.net/gtawiki/images/4/47/Torero-GTAO-front.png/revision/latest?cb=20170614143234"},
    {name = "Cheetah Classic",model = "cheetah2",price = 865000,category = "Sportsk",imglink = "https://static.wikia.nocookie.net/gtawiki/images/3/38/CheetahClassic-GTAO-front.png/revision/latest?cb=20170614143349"},
    {name = "GT500",model = "gt500",price = 785000,category = "Sportsk",imglink = "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTMDaLY83xl6Buo0yT6dC0FUZnrkuQt6Y64rg&usqp=CAU"},
    {name = "Hermes",model = "Hermes",price = 535000,category = "Sportsk",imglink = "https://static.wikia.nocookie.net/gtawiki/images/9/9b/Hermes-GTAO-front.png/revision/latest?cb=20190625095208"},
    {name = "Casco",model = "Casco",price = 904000,category = "Sportsk",imglink = "https://wiki.gtanet.work/images/d/d7/Casco.png"},
    {name = "Coquette Classic",model = "coquette2",price = 665000,category = "Sportsk",imglink = "https://wiki.gtanet.work/images/8/8a/Coquette2.png"},
    {name = "Pigalle",model = "Pigalle",price = 400000,category = "Sportsk",imglink = "https://wiki.gtanet.work/images/7/76/Pigalle.png"},
    {name = "Stinger",model = "Stinger",price = 850000,category = "Sportsk",imglink = "https://wiki.gtanet.work/images/b/b6/Stinger.png"},
    {name = "Stinger GT",model = "stingergt",price = 875000,category = "Sportsk",imglink = "https://wiki.gtanet.work/images/c/c5/StingerGT.png"},
    {name = "Stirling GT",model = "feltzer3",price = 975000,category = "Sportsk",imglink = "https://wiki.gtanet.work/images/0/0b/Feltzer3.png"},
    {name = "Z-Type",model = "ztype",price = 950000,category = "Sportsk",imglink = "https://wiki.gtanet.work/images/3/3a/ZType.png"},

    -- Super
    {name = "Adder",model = "Adder",price = 1000000,category = "super",imglink = "https://wiki.gtanet.work/images/c/c2/Adder.png"},
    {name = "Nero",model = "Nero",price = 1440000,category = "super",imglink = "https://wiki.gtanet.work/images/6/6c/nero.png"},
    {name = "Entity XF",model = "entityxf",price = 795000,category = "super",imglink = "https://wiki.gtanet.work/images/e/e1/EntityXF.png"},
    {name = "Entity XXR",model = "entity2",price = 2305000,category = "super",imglink = "https://i.ytimg.com/vi/nQTMRWOj1fc/maxresdefault.jpg"},
    {name = "811",model = "pfister811",price = 1135000,category = "super",imglink = "https://wiki.gtanet.work/images/8/8e/Pfister811.png"},
    {name = "Cyclone",model = "Cyclone",price = 1890000,category = "super",imglink = "https://www.gtabase.com/images/gta-5/vehicles/super/main/cyclone.jpg"},
    {name = "Reaper",model = "Reaper",price = 1595000,category = "super",imglink = "https://wiki.gtanet.work/images/6/6a/Reaper.png"},
    {name = "Tyrant",model = "Tyrant",price = 2515000,category = "super",imglink = "https://static.wikia.nocookie.net/gtawiki/images/f/f7/Tyrant-GTAO-front.png/revision/latest?cb=20190106193204"},

    -- Muskel Biler
    {name = "Blade",model = "Blade",price = 500,category = "Muskel",imglink = "https://wiki.gtanet.work/images/a/ad/Blade.png"},
    {name = "Bison", model = "Bison", price = Pris, category = "Muskel", imglink = "https://wiki.gtanet.work/images/f/f6/Bison.png"},
    {name = "Buccaneer",model = "Buccaneer",price = 500,category = "Muskel",imglink = "https://wiki.gtanet.work/images/d/de/Buccaneer.png"},
    {name = "Yosemite", model = "Yosemite", price = Pris, category = "Muskel", imglink = "https://static.wikia.nocookie.net/gtawiki/images/0/09/Yosemite-GTAO-front.png/revision/latest?cb=20200612111131"},
    {name = "Chino",model = "Chino",price = 500,category = "Muskel",imglink = "https://wiki.gtanet.work/images/4/4d/Chino.png"},
    {name = "Coquette BlackFin",model = "coquette3",price = 500,category = "Muskel",imglink = "https://wiki.gtanet.work/images/6/67/Coquette3.png"},
    {name = "Bobcat XL", model = "bobcatxl", price = Pris, category = "Muskel", imglink = "https://wiki.gtanet.work/images/d/d8/BobcatXL.png"},
    {name = "Dominator",model = "dominator",price = 500,category = "Muskel",imglink = "https://wiki.gtanet.work/images/6/6e/Dominator.png"},
    {name = "Dukes",model = "Dukes",price = 500,category = "Muskel",imglink = "https://wiki.gtanet.work/images/6/6e/Dukes.png"},
    {name = "Hotknife",model = "Hotknife",price = 500,category = "Muskel",imglink = "https://wiki.gtanet.work/images/1/16/Hotknife.png"},
    {name = "Faction",model = "Faction",price = 500,category = "Muskel",imglink = "https://wiki.gtanet.work/images/5/55/Faction.png"},
    {name = "Nightshade",model = "Nightshade",price = 500,category = "Muskel",imglink = "https://wiki.gtanet.work/images/e/ec/Nightshade.png"},
    {name = "Picador",model = "Picador",price = 500,category = "Muskel",imglink = "https://wiki.gtanet.work/images/1/15/Picador.png"},
    {name = "Sabre Turbo",model = "sabregt",price = 500,category = "Muskel",imglink = "https://wiki.gtanet.work/images/e/eb/SabreGT.png"},
    {name = "Tampa",model = "Tampa",price = 500,category = "Muskel",imglink = "https://wiki.gtanet.work/images/3/30/Tampa.png"},
    {name = "Virgo",model = "Virgo",price = 500,category = "Muskel",imglink = "https://wiki.gtanet.work/images/4/41/Virgo.png"},

    -- Offroad
    {name = "Kamacho", model = "Kamacho", price = 315000, category = "Offroad", imglink = "https://static.wikia.nocookie.net/gtawiki/images/4/47/Kamacho-GTAO-front.png/revision/latest?cb=20190128192114"},
    {name = "Riata", model = "Riata", price = 325000, category = "Offroad", imglink = "https://static.wikia.nocookie.net/gtawiki/images/6/67/Riata-GTAO-front.png/revision/latest?cb=20190821211147"},
    {name = "Streiter", model = "Streiter", price = 235000, category = "Offroad", imglink = "https://cs1.gtaall.eu/attachments/2018-05/original/fc3aa85088c2d3ceb439701e22003c5426b2e9fd/8717-GTA5-2018-05-14-12-31-35-71.jpg"},
    {name = "Bifta", model = "Bifta", price = 75000, category = "Offroad", imglink = "https://wiki.gtanet.work/images/b/b7/Bifta.png"},
    {name = "Blazer", model = "Blazer", price = 10000, category = "Offroad", imglink = "https://wiki.gtanet.work/images/3/3e/Blazer.png"},
    {name = "Brawler", model = "Brawler", price = 715000, category = "Offroad", imglink = "https://wiki.gtanet.work/images/f/fa/Brawler.png"},
    {name = "Bubsta 6x6", model = "dubsta3", price = 375000, category = "Offroad", imglink = "https://wiki.gtanet.work/images/d/d6/Dubsta3.png"},
    {name = "Dune Buggy", model = "dune", price = 200000, category = "Offroad", imglink = "https://wiki.gtanet.work/images/c/c6/Dune.png"},
    {name = "Rebel", model = "rebel2", price = 220000, category = "Offroad", imglink = "https://wiki.gtanet.work/images/9/90/Rebel2.png"},
    {name = "Nagasaki Street Blazer", model = "blazer4", price = 35000, category = "Offroad", imglink = "https://static.wikia.nocookie.net/gtawiki/images/6/6e/StreetBlazer-GTAO-front.png/revision/latest?cb=20161004180649"},
    
    -- Suver 
    {name = "Baller", model = "baller", price = 60000, category = "Suver", imglink = "https://wiki.gtanet.work/images/7/79/Baller.png"},
    {name = "Baller 2", model = "baller2", price = 90000, category = "Suver", imglink = "https://wiki.gtanet.work/images/9/98/Baller2.png"},
    {name = "Baller LE", model = "baller3", price = 149000, category = "Suver", imglink = "https://wiki.gtanet.work/images/9/9b/Baller3.png"},
    {name = "Baller LE LWD", model = "baller4", price = 247000, category = "Suver", imglink = "https://wiki.gtanet.work/images/e/e8/Baller4.png"},
    {name = "Dubsta", model = "Dubsta", price = 1245000, category = "Suver", imglink = "https://wiki.gtanet.work/images/e/ec/Dubsta.png"},
    {name = "Dubsta 2", model = "Dubsta2", price = 249000, category = "Suver", imglink = "https://wiki.gtanet.work/images/3/36/Dubsta2.png"},
    {name = "Toros", model = "Toros", price = 498000, category = "Suver", imglink = "https://static.wikia.nocookie.net/gtawiki/images/d/d3/Toros-GTAO-front.png/revision/latest?cb=20181214174204"},
    {name = "Contender", model = "Contender", price = 250000, category = "Suver", imglink = "https://wiki.gtanet.work/images/2/2e/Contender.png"},
    {name = "XLS", model = "XLS", price = 253000, category = "Suver", imglink = "https://wiki.gtanet.work/images/f/fa/XLS.png"},
    {name = "Rocoto", model = "Rocoto", price = 85000, category = "Suver", imglink = "https://wiki.gtanet.work/images/2/23/Rocoto.png"},

    -- Varevogne
    {name = "Moonbeam", model = "moonbeam2", price = 450000, category = "Varevogne", imglink = "https://wiki.gtanet.work/images/c/c1/Moonbeam2.png"},
    {name = "Gang Burrito", model = "gburrito", price = 245000, category = "Varevogne", imglink = "https://wiki.gtanet.work/images/b/b0/GBurrito.png"},
    {name = "Journey", model = "Journey", price = 150000, category = "Varevogne", imglink = "https://wiki.gtanet.work/images/0/0c/Journey.png"},
    {name = "Paradise", model = "Paradise", price = 250000, category = "Varevogne", imglink = "https://wiki.gtanet.work/images/b/b3/Paradise.png"},
    {name = "Rumpo", model = "Rumpo", price = 130000, category = "Varevogne", imglink = "https://wiki.gtanet.work/images/9/9f/Rumpo.png"},
    {name = "Surfer", model = "Surfer", price = 130000, category = "Varevogne", imglink = "https://wiki.gtanet.work/images/d/d7/Surfer.png"},
    {name = "Youga", model = "Youga", price = 160000, category = "Varevogne", imglink = "https://wiki.gtanet.work/images/d/d5/Youga.png"},
    {name = "Youga 2", model = "Youga2", price = 150000, category = "Varevogne", imglink = "https://wiki.gtanet.work/images/e/e6/Youga2.png"},

    -- Sedan
    {name = "Raiden", model = "Raiden", price = 2500000, category = "Sedan", imglink = "https://i.ytimg.com/vi/6DmFOroDFtQ/hqdefault.jpg"},
    {name = "Asea", model = "Asea", price = 200000, category = "Sedan", imglink = "https://wiki.gtanet.work/images/c/ce/Asea.png"},
    {name = "Cognoscenti", model = "Cognoscenti", price = 2200000, category = "Sedan", imglink = "https://wiki.gtanet.work/images/5/51/Cognoscenti.png"},
    {name = "Cognoscenti 55", model = "cog55", price = 2000000, category = "Sedan", imglink = "https://wiki.gtanet.work/images/d/d5/Cog55.png"},
    {name = "Glendale", model = "Glendale", price = 400000, category = "Sedan", imglink = "https://wiki.gtanet.work/images/b/b2/Glendale.png"},
    {name = "Ingot", model = "Ingot", price = 85000, category = "Sedan", imglink = "https://wiki.gtanet.work/images/7/74/Ingot.png"},
    {name = "Intruder", model = "Intruder", price = 120000, category = "Sedan", imglink = "https://wiki.gtanet.work/images/9/92/Intruder.png"},
    {name = "Premier", model = "Premier", price = 150000, category = "Sedan", imglink = "https://wiki.gtanet.work/images/9/9d/Premier.png"},
    {name = "Primo", model = "Primo", price = 100000, category = "Sedan", imglink = "https://wiki.gtanet.work/images/4/45/Primo.png"},
    {name = "Primo Custom", model = "Primo2", price = 200000, category = "Sedan", imglink = "https://wiki.gtanet.work/images/3/30/Primo2.png"},
    {name = "Regina", model = "Regina", price = 100000, category = "Sedan", imglink = "https://wiki.gtanet.work/images/5/5f/Regina.png"},
    {name = "Schafter", model = "Schafter", price = 650000, category = "Sedan", imglink = "https://wiki.gtanet.work/images/c/cc/Schafter2.png"},
    {name = "Stanier", model = "Stanier", price = 100000, category = "Sedan", imglink = "https://wiki.gtanet.work/images/5/57/Stanier.png"},
    {name = "Super Diamond", model = "superd", price = 1500000, category = "Sedan", imglink = "https://wiki.gtanet.work/images/6/6e/Superd.png"},
    {name = "Stratum", model = "Stratum", price = 100000, category = "Sedan", imglink = "https://wiki.gtanet.work/images/b/ba/Stratum.png"},
    {name = "Surge", model = "Surge", price = 240000, category = "Sedan", imglink = "https://wiki.gtanet.work/images/1/1a/Surge.png"},
    {name = "Tailgater", model = "Tailgater", price = 320000, category = "Sedan", imglink = "https://wiki.gtanet.work/images/a/af/Tailgater.png"},
    {name = "Warrener", model = "Warrener", price = 150000, category = "Sedan", imglink = "https://wiki.gtanet.work/images/2/22/Warrener.png"},

    -- Motorcykel
    {name = "Akuma", model = "Akuma", price = 90000, category = "Motorcykler", imglink = "https://wiki.gtanet.work/images/1/16/Akuma.png"},
    {name = "Bagger", model = "Bagger", price = 50000, category = "Motorcykler", imglink = "https://wiki.gtanet.work/images/6/64/Bagger.png"},
    {name = "Bati 801", model = "bati", price = 350000, category = "Motorcykler", imglink = "https://wiki.gtanet.work/images/c/ce/Bati.png"},
    {name = "Bati 801RR", model = "bati2", price = 350000, category = "Motorcykler", imglink = "https://wiki.gtanet.work/images/6/60/Bati2.png"},
    {name = "BF400", model = "BF400", price = 195000, category = "Motorcykler", imglink = "https://wiki.gtanet.work/images/3/3a/BF400.png"},
    {name = "Carbon RS", model = "carbonrs", price = 180000, category = "Motorcykler", imglink = "https://wiki.gtanet.work/images/d/d3/CarbonRS.png"},
    {name = "Cliffhanger", model = "Cliffhanger", price = 325000, category = "Motorcykler", imglink = "https://wiki.gtanet.work/images/1/12/Cliffhanger.png"},
    {name = "Double T", model = "double", price = 112000, category = "Motorcykler", imglink = "https://wiki.gtanet.work/images/0/01/Double.png"},
    {name = "Faggio", model = "Faggio2", price = 14000, category = "Motorcykler", imglink = "https://wiki.gtanet.work/images/2/25/Faggio2.png"},
    {name = "Knallert", model = "Faggio", price = 18000, category = "Motorcykler", imglink = "https://www.gtabase.com/images/gta-5/vehicles/motorcycles/main/faggio.jpg"},
    {name = "Gargoyle", model = "Gargoyle", price = 220000, category = "Motorcykler", imglink = "https://wiki.gtanet.work/images/4/44/Gargoyle.png"},
    {name = "Innovation", model = "Innovation", price = 190000, category = "Motorcykler", imglink = "https://wiki.gtanet.work/images/4/42/Innovation.png"},
    {name = "PCJ-600", model = "pcj", price = 90000, category = "Motorcykler", imglink = "https://wiki.gtanet.work/images/f/f5/PCJ.png"},
    {name = "Zombie Chobber", model = "zombieb", price = 385000, category = "Motorcykler", imglink = "https://static.wikia.nocookie.net/gtawiki/images/a/af/ZombieBobber-GTAO-front.png/revision/latest?cb=20161004181721"},
    {name = "Vindicator", model = "Vindicator", price = 600000, category = "Motorcykler", imglink = "https://wiki.gtanet.work/images/b/bb/Vindicator.png"},
    {name = "Sanchez", model = "Sanchez", price = 100000, category = "Motorcykler", imglink = "https://wiki.gtanet.work/images/5/52/Sanchez.png"},
    {name = "Nightblade", model = "Nightblade", price = 400000, category = "Motorcykler", imglink = "https://static.wikia.nocookie.net/gtawiki/images/8/8e/Nightblade-TLAD-front.png/revision/latest?cb=20170921193041"},
}

cfg.categories = {
    {name = "super",label = "Super"},
    {name = "Sedan",label = "Sedan"},
	{name = "Motorcykler",label = "Motorcykel/Knallert"},
	{name = "Coupéer",label = "Coupéer"},
    {name = "Kompakte",label = "Kompakte"},
    {name = "Sportsk",label = "Sports klassikere"},
    {name = "SportsBi",label = "Sports"},
    {name = "Muskel",label = "Muskel biler"},
    {name = "Offroad",label = "Offroad"},
    {name = "Suver",label = "Suver"},
    {name = "Varevogne",label = "Varevogne"},
}

return cfg